[package]
name = "serializer"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
deku = "0.16.0"
wasm-bindgen = "0.2.100"
paste = "1.0.6"
serde = { version = "1.0.183", features = ["derive"] }
serde_json = "1.0.104"
serde-wasm-bindgen = "0.5.0"
