[package]
name = "simulate"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
path = "src/lib.rs"
name = "simulate"

[[bin]]
name = "simulate"
path = "src/main.rs"

[dependencies]
rand = "0.8.5"
